### ISSUE TITLE
RenderSection doesnt seem to work.

### ISSUE THREAD

**Issue by nmolzach** [karthik25/sblog.net#8]
So, in my layout, i want the tags for an individual post to show in the sidebar, so to do this i used RenderSection but it refuses to render... even debugging it just glances right over it, any ideas?

in my _Layout:

```
    @RenderSection("tags", false)
```

the tags themselves:

```
@section tags { 

<h3 class="section-title">Tags</h3>
<div class="widget tags-wr">
    <ul class="tags-list">
        @foreach(var t in Model.Post.Tags)
        {
        }
        @if (Model.Count > 0)
        {
            foreach (var tag in Model.Where(tag => tag.IsTagEntityValid()))
            {                                           
              <li><i class="fa fa-tags"></i> @Html.RouteLink(tag.TagName, "Tag", new { tagName = tag.TagSlug })  </li>
            }
        }
        else
        {
              <li><i class="fa fa-tags"></i>No tags!</li>
        }
    </ul>
</div>
}
```

**Comment by karthik25** [comment]
Hello Zach, I will check this out tonight and get back to you! Thanks for your interest!

**Comment by karthik25** [comment]
Hello Zach, sorry was held up w/ a lot of things, so never got to this. I tried this and it seems to work for me. Here is what I did:

In the _Layout.cshtml file (I used the BootswatchAmelia theme), I added

``` html
@* snip *@
@Html.Partial("SiteActions")
@RenderSection("tags", false)
@* snip *@
```

And then in the sBlog.Net\Views\Home\View.cshtml view, I added the following

``` html
@section tags {
    @foreach (var tag in Model.Post.Tags)
    {
        <h2>@tag.TagName</h2><br/>        
    }
}
```

This worked for me. Can you try this out? One reason it didn't work for you could be based on where you are trying to render content for this section. Was that in a partial view? That may not work w/ RenderSection
